//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Login_ID { get; set; }
        public string Password { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Create_Datetime { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
