//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int PaymentType_ID { get; set; }
        public string PaymentType_Name { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Update_Datetime { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
