//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomMovie = new HashSet<RoomMovie>();
            this.Seat = new HashSet<Seat>();
        }
    
        public int Room_ID { get; set; }
        public string Room_Name { get; set; }
        public int Theater_ID { get; set; }
        public int RoomType_ID { get; set; }
        public string Seat_Pattern { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Update_Datetime { get; set; }
    
        public virtual RoomType RoomType { get; set; }
        public virtual Theater Theater { get; set; }
        public virtual ICollection<RoomMovie> RoomMovie { get; set; }
        public virtual ICollection<Seat> Seat { get; set; }
    }
}
