//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMovie
    {
        public RoomMovie()
        {
            this.Booking = new HashSet<Booking>();
            this.SeatMovie = new HashSet<SeatMovie>();
        }
    
        public int RoomMovie_ID { get; set; }
        public int Room_ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int Movie_ID { get; set; }
        public double Price { get; set; }
        public bool Publish { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Update_Datetime { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<SeatMovie> SeatMovie { get; set; }
    }
}
