//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Seat_ID { get; set; }
        public string Seat_Name { get; set; }
        public int Room_ID { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Update_Datetime { get; set; }
        public int Rows { get; set; }
        public int Columns { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
