//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theater
    {
        public Theater()
        {
            this.Room = new HashSet<Room>();
        }
    
        public int Theater_ID { get; set; }
        public string Theater_Name { get; set; }
        public string Theater_Address { get; set; }
        public string Theater_Phone_No { get; set; }
        public bool Active_Indicator { get; set; }
        public System.DateTime Update_Datetime { get; set; }
    
        public virtual ICollection<Room> Room { get; set; }
    }
}
